version: "3.7"

services:
  nodeapp:
    build: .
    init: true
    image: tobacco-marshal-back:v1.0.0
    restart: "always"
    env_file:
      - ./.env
    ports:
      - 80:$PORT
    networks:
      - ngnet

networks:
  ngnet:
    name: ngnet
    driver: bridge
